from pydantic import BaseModel, Field
from app.schemas.base_schema import OutputSchema


class CreateSchema(BaseModel):
    # Generated by the server as a 50-character alphanumeric value.
    fd_random: str | None = Field(default=None, max_length=50)
    pm_4d802b91: str = Field(min_length=36, max_length=36)
    fd_reservation_key: str = Field(min_length=1, max_length=50)


class UpdateSchema(BaseModel):
    fd_random: str | None = Field(default=None, max_length=50)
    pm_4d802b91: str | None = Field(default=None, min_length=36, max_length=36)
    fd_reservation_key: str | None = Field(default=None, min_length=1, max_length=50)


class ReleaseReservationSchema(BaseModel):
    fd_reservation_key: str = Field(min_length=1, max_length=50)


class ResponseSchema(OutputSchema):
    fd_random: str
    # Existing records, created before the survey relation was introduced,
    # remain readable while new records always include this value.
    pm_4d802b91: str | None = None
    fd_reservation_key: str | None = None
